name: snaply
description: A Flutter plugin for instant bug reports with screenshots, screen recordings, device environment and logs.
version: 0.0.1-alpha.4
repository: https://github.com/mr-stan-dev/snaply-flutter-plugin
issue_tracker: https://github.com/mr-stan-dev/snaply-flutter-plugin/issues
homepage: https://snaply.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.1.1
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.snaply.flutter_android
        pluginClass: SnaplyPlugin
      ios:
        pluginClass: SnaplyPlugin
